name: Build Docker image and push to Docker Hub

on:
  push:
    branches: main

job: 
  build-and-push:
    runs-on: ubutu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3
     
     -name: Set data as tag
      id: date
      run: echo "::set-output name=DATE::$(TZ-Asia/Tokyo date + '%Y%m%d%H%M%')"
   
    -name: Log in to Docker Hub
     uses: docker/login-action@v2.0.0
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

    -name: Build and push
     uses: docker/login-action@v3
     with:
      context:
      push: true
      tag: ${{ secrets.DOCKERHUB_USERNAME }}/docker-cicd:${{ steps.date.outputs.DATE }}      
      
